name: 'Terraform Plan & Apply'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    location: westeurope
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    RESOURCE_GROUP: fozz-RG # Must already be created via backend.yaml
    STORAGE_ACCOUNT: safozzmanagementweu # Must already be created via backend.yaml

jobs:
  terraform:
        name: Deploy to Azure
        runs-on: ubuntu-latest
        # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
        defaults:
          run:
            working-directory: .github/Terraform
            shell: bash

        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        # Install the latest version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.

        # NB hardcoded storage account & RG name
        - name: Terraform Init
          run: |
            terraform init \
              -backend-config="resource_group_name=$RESOURCE_GROUP" \
              -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
              -backend-config="container_name=tfstate" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="use_oidc=true"


        - name: Terraform Format
          run: terraform fmt -recursive

        # Validate before Planning
        - name: Terraform Validate
          run: terraform validate 


        - name: Terraform Plan
          run: terraform plan -input=false -var location=$location -var environment=$environment
          
        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false -var location=$location -var environment=$environment